IDK what i'm doing
Pinduca23/little_projects pull request #1
Opened 2021-12-07 13:29 UTC by Pinduca23

Yes

2021-12-07 14:19 UTC, plinioh requested changes

2021-12-07 14:19 UTC, plinioh commented on PassPy/password_manager.py
> +    while pass_length < 4:
```suggestion
    pass_length = 0
    while pass_length < 4:
```

2021-12-07 14:19 UTC, plinioh commented on PassPy/password_manager.py
> +            print('\nPassword must have at least 4 characters or words')
```suggestion

```

2021-12-07 14:19 UTC, plinioh commented on PassPy/password_manager.py
>              pass_length = int(input('\nRequired size of password: '))
```suggestion
            pass_length = int(input('\nRequired size of password: '))
            if pass_length < 4:
               print('\nPassword must have at least 4 characters or words')
```

2021-12-08 10:46 UTC, Pinduca23 commented
Commit after code review

2021-12-08 10:46 UTC, merged